apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
  namespace: ecommerce
data:
  DB_HOST: "ecommerce-prod-primary.cluster-xxxx.us-east-2.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "ecommerce"
  REDIS_HOST: "ecommerce-prod-sessions.xxxx.0001.use2.cache.amazonaws.com"
  REDIS_PORT: "6379"
  AWS_REGION: "us-east-2"
  SNS_ORDER_TOPIC: "arn:aws:sns:us-east-2:866934333672:ecommerce-prod-order-events"
  SNS_PAYMENT_TOPIC: "arn:aws:sns:us-east-2:866934333672:ecommerce-prod-payment-events"
  SQS_ORDER_QUEUE: "https://sqs.us-east-2.amazonaws.com/866934333672/ecommerce-prod-order-processing"
  SQS_PAYMENT_QUEUE: "https://sqs.us-east-2.amazonaws.com/866934333672/ecommerce-prod-payment-processing"
  NODE_ENV: "production"
  LOG_LEVEL: "info"
